# Copyright (C) 2019-2025
# Julian Valentin, Daniel Spitzer, LTeX+ Development Community
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

name: "CI"

on:
  push:
    branches:
      - "*"
    tags:
      - "*"
  pull_request:
    branches:
      - "develop"
  workflow_dispatch:
    inputs:
      publish_docker:
        description: "Also build and push the container image"
        required: true
        type: boolean
        default: false

jobs:
  build:
    name: "CI - Build Job"
    runs-on: "${{ matrix.os }}"
    permissions:
      contents: read

    strategy:
      matrix:
        os:
          - "ubuntu-latest"
          - "macos-latest"
          - "windows-latest"

    steps:
      - name: "Checkout Repository"
        uses: "actions/checkout@v6"

      - name: "Set up Java"
        uses: "actions/setup-java@v5"
        with:
          java-version: "21"
          distribution: "temurin"

      - name: "Set up Python"
        uses: "actions/setup-python@v6"
        with:
          python-version: "3.13"

      - name: "Build LTeX+ LS"
        run: "mvn -B -e verify"
        env:
          LANGUAGETOOL_USERNAME: ${{ secrets.LANGUAGETOOL_USERNAME }}
          LANGUAGETOOL_API_KEY: ${{ secrets.LANGUAGETOOL_API_KEY }}

  validate:
    name: "CI - Validate Job"
    runs-on: "ubuntu-latest"
    permissions:
      contents: read
    steps:
      - name: "Checkout Repository"
        uses: "actions/checkout@v6"

      - name: "Set up Python"
        uses: "actions/setup-python@v6"
        with:
          python-version: "3.13"

      - name: "Install Python Dependencies"
        run: "python -u -m pip install --upgrade pip && pip install xmlschema"

      - name: "Validate .assembly.xml"
        run: "python -u -c 'import xmlschema; xmlschema.XMLSchema(\"schemas/assembly-2.1.0.xsd\").validate(\".assembly.xml\")'"

      - name: "Validate changelog.xml"
        run: "python -u -c 'import xmlschema; xmlschema.XMLSchema(\"schemas/changes-1.0.0.xsd\").validate(\"changelog.xml\")'"

      - name: "Validate pom.xml"
        run: "python -u -c 'import xmlschema; xmlschema.XMLSchema(\"schemas/maven-4.0.0.xsd\").validate(\"pom.xml\")'"

      - name: "Check Source Consistency"
        run: "python -u tools/checkSourceConsistency.py"

  get-version:
    name: "CI - Get Version Job"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      ltex_ls_version: ${{ steps.meta.outputs.ltex_ls_version }}
      ltex_ls_is_prerelease: ${{ steps.meta.outputs.ltex_ls_is_prerelease }}
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v6

      - name: "Set up Python"
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: "Install Python Dependencies"
        run: python -u -m pip install --upgrade pip && pip install semver

      - name: "Compute metadata"
        id: meta
        run: |
          LTEX_LS_VERSION="$(python -u -c "import re; print(re.search(r'<version>(.*?)</version>', open('pom.xml', 'r').read()).group(1), end='')")"
          if [[ -z "$LTEX_LS_VERSION" ]]; then
            echo "Error: LTEX_LS_VERSION not set"
            exit 1
          fi

            LTEX_LS_IS_PRERELEASE="$(python -u -c "import semver; print('true' if semver.VersionInfo.parse('${LTEX_LS_VERSION}').prerelease is not None else 'false', end='')")"

            echo "ltex_ls_version=$LTEX_LS_VERSION" >> "$GITHUB_OUTPUT"
            echo "ltex_ls_is_prerelease=$LTEX_LS_IS_PRERELEASE" >> "$GITHUB_OUTPUT"

  deploy:
    name: "CI - Deploy Job"
    needs:
      - "build"
      - "validate"
      - "get-version"
    if: "${{ startsWith(github.ref, 'refs/tags/') }}"
    runs-on: "ubuntu-latest"
    permissions:
      contents: write
    steps:
      - name: "Checkout Repository"
        uses: "actions/checkout@v6"

      - name: "Set up Java"
        uses: "actions/setup-java@v5"
        with:
          java-version: "21"
          distribution: "temurin"

      - name: "Set up Python"
        uses: "actions/setup-python@v6"
        with:
          python-version: "3.13"

      - name: "Install Python Dependencies"
        run: "python -u -m pip install --upgrade pip && pip install semver"

      - name: "Set LTEX_LS_CHANGELOG"
        run: |
          if [ "${{ needs.get-version.outputs.ltex_ls_is_prerelease }}" = "false" ]; then
            echo "LTEX_LS_CHANGELOG<<EOF" >> "$GITHUB_ENV"
            python -u tools/convertChangelog.py --xml-file changelog.xml --version latest >> "$GITHUB_ENV"
            echo "EOF" >> "$GITHUB_ENV"
          else
            echo "LTEX_LS_CHANGELOG=This is a pre-release. Use at your own risk." >> "$GITHUB_ENV"
          fi

      - name: "Build LTeX+ LS"
        run: "mvn -B -e package"

      - name: "Create Binary Archives"
        run: "python -u tools/createBinaryArchives.py"

      - name: "Create GitHub Release"
        run: >
          gh release create ${{ github.ref_name }}
          --prerelease=${{ needs.get-version.outputs.ltex_ls_is_prerelease }}
          --title='${{ needs.get-version.outputs.ltex_ls_version }}'
          --notes='${{ env.LTEX_LS_CHANGELOG }}'
          'target/ltex-ls-plus-${{ needs.get-version.outputs.ltex_ls_version }}.tar.gz'
          'target/ltex-ls-plus-${{ needs.get-version.outputs.ltex_ls_version }}-linux-x64.tar.gz'
          'target/ltex-ls-plus-${{ needs.get-version.outputs.ltex_ls_version }}-mac-x64.tar.gz'
          'target/ltex-ls-plus-${{ needs.get-version.outputs.ltex_ls_version }}-windows-x64.zip'
          'target/ltex-ls-plus-${{ needs.get-version.outputs.ltex_ls_version }}-linux-aarch64.tar.gz'
          'target/ltex-ls-plus-${{ needs.get-version.outputs.ltex_ls_version }}-mac-aarch64.tar.gz'
          'target/ltex-ls-plus-${{ needs.get-version.outputs.ltex_ls_version }}-windows-aarch64.zip'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  docker:
    name: "CI - Deploy Container Image Job"
    needs:
      - "build"
      - "validate"
      - "get-version"
    if: >-
      ${{
        startsWith(github.ref, 'refs/tags/') ||
        (github.event_name == 'workflow_dispatch' && inputs.publish_docker)
      }}
    runs-on: "ubuntu-latest"
    permissions:
      contents: read
      packages: write

    steps:
      - name: "Checkout Repository"
        uses: "actions/checkout@v6"

      - name: "Set up QEMU"
        uses: "docker/setup-qemu-action@v4"
        with:
          platforms: "amd64,arm64"

      - name: "Set up Buildx"
        uses: "docker/setup-buildx-action@v4"

      - name: "Log in to GHCR"
        uses: "docker/login-action@v4"
        with:
          registry: "ghcr.io"
          username: "${{ github.actor }}"
          password: "${{ secrets.GITHUB_TOKEN }}"

      - name: "Compute Tags and Labels"
        id: "meta"
        uses: "docker/metadata-action@v6"
        with:
          images: "ghcr.io/${{ github.repository_owner }}/ltex-ls-plus"
          tags: |
            type=ref,event=tag
            type=raw,value=${{ format('{0}-test-image', needs.get-version.outputs.ltex_ls_version) }},enable=${{ github.event_name == 'workflow_dispatch' }}

      - name: "Build and Push"
        uses: "docker/build-push-action@v7"
        with:
          platforms: linux/amd64,linux/arm64
          context: "."
          file: "./Dockerfile"
          push: true
          build-args: |
            LTEX_VERSION=${{ needs.get-version.outputs.ltex_ls_version }}
            SOURCE_MODE=from-local
          tags: "${{ steps.meta.outputs.tags }}"
          labels: "${{ steps.meta.outputs.labels }}"
